"""Data models and schemas."""

from .application import (
    LEGAL_ATTEMPT_TRANSITIONS,
    ApplicationAttempt,
    ApplicationResult,
    ApplicationStatus,
    AttemptPreflightResult,
    AttemptStatus,
    AttemptTransitionResult,
    DocumentBundle,
)
from .job import JobPosting, QualificationResult
from .telegram import (
    CorrelationConsumeResult,
    CorrelationLeaseResult,
    CorrelationRegisterResult,
    CorrelationReplyResult,
    CorrelationStatus,
    CorrelationWaitResult,
    OutboxChunk,
    OutboxClaimResult,
    OutboxDeliveryResult,
    OutboxDrainResult,
    OutboxEnqueueResult,
    OutboxRecord,
    OutboxStatus,
    TelegramCorrelation,
    TelegramCursor,
)

__all__ = [
    "JobPosting",
    "QualificationResult",
    "ApplicationStatus",
    "AttemptStatus",
    "AttemptPreflightResult",
    "AttemptTransitionResult",
    "ApplicationAttempt",
    "LEGAL_ATTEMPT_TRANSITIONS",
    "DocumentBundle",
    "ApplicationResult",
    "OutboxStatus",
    "CorrelationStatus",
    "OutboxChunk",
    "OutboxRecord",
    "OutboxEnqueueResult",
    "OutboxClaimResult",
    "OutboxDeliveryResult",
    "OutboxDrainResult",
    "TelegramCorrelation",
    "TelegramCursor",
    "CorrelationRegisterResult",
    "CorrelationLeaseResult",
    "CorrelationReplyResult",
    "CorrelationConsumeResult",
    "CorrelationWaitResult",
]
